# Configuration file for GeoPressureR parameters
#
# This file stores all the parameters used by the GeoPressureR functions, following the best
# practice to separate parameters from codes. This file is used with the config R package
# <https://rstudio.github.io/config/> which allows to retrieve the value of each parameter
# in your analysis files.
#
# This file is meant to be adapted based on your needs: feel free to add or remove parameters either
# in the default or for each tag. It is recommended to specify all parameters used, even if you
# use the default value.

default:
  crop_start: NULL
  crop_end: NULL
  #-- SET MAP
  scale: 3 # 1 (min) -> 1째 ; 2 -> 0.5째 ; 5 -> 0.25째 ; 10 (max) -> 0.1째
  include_min_duration: 0 # in hours
  #-- GEOPRESSURE
  max_sample: 250
  margin: 20 # in hPa
  sd: 1
  thr_mask: 0.9
  # log_linear_pooling_weight:
  #-- GRAPH
  thr_likelihood: 0.99
  thr_gs: 150 # km/h
  thr_as: 90 # km/h
  #-- MOVEMENT MODEL
  movement_low_speed_fix: 15 # km/h

91D:
  id: "91D"
  extent: !expr c(6, 40, -20, 57) # c(W, E, S, N)
  thr_gs: 120
  scientific_name: "Luscinia luscinia"

969:
  id: "969"
  extent: !expr c(4, 34, -23, 63) # c(W, E, S, N)
  scientific_name: "Gallinago media"

1F3:
  id: "1F3"
  extent: !expr c(6, 40, -23, 59)
  scientific_name: "Caprimulgus europaeus"
  include_min_duration: 12
